// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api.sql

package db

import (
	"context"
)

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = ?
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIToken, id)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, name, token_hash, user_agent, source_ip, created_at, last_used_at, expires_at
FROM api_tokens WHERE token_hash = ?
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.UserAgent,
		&i.SourceIp,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertAPIToken = `-- name: InsertAPIToken :exec
INSERT INTO api_tokens (id, name, token_hash, user_agent, source_ip, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAPITokenParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	UserAgent string `json:"user_agent"`
	SourceIp  string `json:"source_ip"`
	CreatedAt int64  `json:"created_at"`
	ExpiresAt *int64 `json:"expires_at"`
}

func (q *Queries) InsertAPIToken(ctx context.Context, arg InsertAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, insertAPIToken,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.UserAgent,
		arg.SourceIp,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, token_hash, user_agent, source_ip, created_at, last_used_at, expires_at
FROM api_tokens ORDER BY created_at, id
`

func (q *Queries) ListAPITokens(ctx context.Context) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.UserAgent,
			&i.SourceIp,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = ? WHERE id = ?
`

type TouchAPITokenParams struct {
	LastUsedAt *int64 `json:"last_used_at"`
	ID         string `json:"id"`
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, arg.LastUsedAt, arg.ID)
	return err
}
