// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: community.sql

package db

import (
	"context"
)

const bumpCommunityRevision = `-- name: BumpCommunityRevision :one
UPDATE community_accounts SET revision = revision + 1 WHERE account = ? RETURNING revision
`

func (q *Queries) BumpCommunityRevision(ctx context.Context, account string) (int64, error) {
	row := q.db.QueryRowContext(ctx, bumpCommunityRevision, account)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const clearCommunityHistoryThrough = `-- name: ClearCommunityHistoryThrough :execrows
DELETE FROM community_messages WHERE account = ? AND conversation_id = ? AND id <= ?3
AND state IN ('received', 'sent', 'failed', 'cancelled')
`

type ClearCommunityHistoryThroughParams struct {
	Account        string `json:"account"`
	ConversationID int64  `json:"conversation_id"`
	ThroughID      int64  `json:"through_id"`
}

func (q *Queries) ClearCommunityHistoryThrough(ctx context.Context, arg ClearCommunityHistoryThroughParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearCommunityHistoryThrough, arg.Account, arg.ConversationID, arg.ThroughID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const communityHistoryInfo = `-- name: CommunityHistoryInfo :one
SELECT
    (SELECT CAST(coalesce(max(m.id), 0) AS INTEGER) FROM community_messages m WHERE m.account = ?1 AND m.conversation_id = ?2 AND m.state <> 'held') AS latest_id,
    (SELECT count(*) FROM community_messages n WHERE n.account = ?1 AND n.conversation_id = ?2 AND n.state <> 'held' AND n.id > ?3) AS newer_count
`

type CommunityHistoryInfoParams struct {
	Account        string `json:"account"`
	ConversationID int64  `json:"conversation_id"`
	NewerThan      int64  `json:"newer_than"`
}

type CommunityHistoryInfoRow struct {
	LatestID   int64 `json:"latest_id"`
	NewerCount int64 `json:"newer_count"`
}

func (q *Queries) CommunityHistoryInfo(ctx context.Context, arg CommunityHistoryInfoParams) (CommunityHistoryInfoRow, error) {
	row := q.db.QueryRowContext(ctx, communityHistoryInfo, arg.Account, arg.ConversationID, arg.NewerThan)
	var i CommunityHistoryInfoRow
	err := row.Scan(&i.LatestID, &i.NewerCount)
	return i, err
}

const communityUnreadTotals = `-- name: CommunityUnreadTotals :one
SELECT count(m.id) AS unread, CAST(coalesce(sum(m.mention), 0) AS INTEGER) AS mentions
FROM community_conversations c
JOIN community_messages m ON m.account = c.account AND m.conversation_id = c.id
WHERE c.account = ? AND m.id > c.read_through AND m.direction = 'incoming' AND m.state = 'received'
`

type CommunityUnreadTotalsRow struct {
	Unread   int64 `json:"unread"`
	Mentions int64 `json:"mentions"`
}

func (q *Queries) CommunityUnreadTotals(ctx context.Context, account string) (CommunityUnreadTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, communityUnreadTotals, account)
	var i CommunityUnreadTotalsRow
	err := row.Scan(&i.Unread, &i.Mentions)
	return i, err
}

const countCommunitySettings = `-- name: CountCommunitySettings :one
SELECT
    (SELECT COUNT(*) FROM community_rules WHERE community_rules.account = ?1) AS rules,
    (SELECT COUNT(*) FROM community_aliases WHERE community_aliases.account = ?1) AS aliases
`

type CountCommunitySettingsRow struct {
	Rules   int64 `json:"rules"`
	Aliases int64 `json:"aliases"`
}

func (q *Queries) CountCommunitySettings(ctx context.Context, account string) (CountCommunitySettingsRow, error) {
	row := q.db.QueryRowContext(ctx, countCommunitySettings, account)
	var i CountCommunitySettingsRow
	err := row.Scan(&i.Rules, &i.Aliases)
	return i, err
}

const deleteCommunityAlias = `-- name: DeleteCommunityAlias :execrows
DELETE FROM community_aliases WHERE account = ? AND name = ?
`

type DeleteCommunityAliasParams struct {
	Account string `json:"account"`
	Name    string `json:"name"`
}

func (q *Queries) DeleteCommunityAlias(ctx context.Context, arg DeleteCommunityAliasParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCommunityAlias, arg.Account, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCommunityBuddy = `-- name: DeleteCommunityBuddy :execrows
DELETE FROM community_buddies WHERE account = ? AND username = ?
`

type DeleteCommunityBuddyParams struct {
	Account  string `json:"account"`
	Username string `json:"username"`
}

func (q *Queries) DeleteCommunityBuddy(ctx context.Context, arg DeleteCommunityBuddyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCommunityBuddy, arg.Account, arg.Username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCommunityInterest = `-- name: DeleteCommunityInterest :execrows
DELETE FROM community_interests WHERE account = ? AND item = ?
`

type DeleteCommunityInterestParams struct {
	Account string `json:"account"`
	Item    string `json:"item"`
}

func (q *Queries) DeleteCommunityInterest(ctx context.Context, arg DeleteCommunityInterestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCommunityInterest, arg.Account, arg.Item)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCommunityRule = `-- name: DeleteCommunityRule :execrows
DELETE FROM community_rules WHERE account = ? AND id = ?
`

type DeleteCommunityRuleParams struct {
	Account string `json:"account"`
	ID      int64  `json:"id"`
}

func (q *Queries) DeleteCommunityRule(ctx context.Context, arg DeleteCommunityRuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCommunityRule, arg.Account, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteHeldCommunityMessages = `-- name: DeleteHeldCommunityMessages :execrows
DELETE FROM community_messages WHERE account = ? AND sender = ? AND state = 'held' AND id <= ?3
`

type DeleteHeldCommunityMessagesParams struct {
	Account   string `json:"account"`
	Sender    string `json:"sender"`
	ThroughID int64  `json:"through_id"`
}

func (q *Queries) DeleteHeldCommunityMessages(ctx context.Context, arg DeleteHeldCommunityMessagesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteHeldCommunityMessages, arg.Account, arg.Sender, arg.ThroughID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const editCommunityAccount = `-- name: EditCommunityAccount :execrows
UPDATE community_accounts SET description = ?, accept_invitations = ?, retention_days = ?, public_feed_logging = ?, revision = revision + 1
WHERE account = ? AND revision = ?
`

type EditCommunityAccountParams struct {
	Description       string `json:"description"`
	AcceptInvitations int64  `json:"accept_invitations"`
	RetentionDays     int64  `json:"retention_days"`
	PublicFeedLogging int64  `json:"public_feed_logging"`
	Account           string `json:"account"`
	Revision          int64  `json:"revision"`
}

func (q *Queries) EditCommunityAccount(ctx context.Context, arg EditCommunityAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, editCommunityAccount,
		arg.Description,
		arg.AcceptInvitations,
		arg.RetentionDays,
		arg.PublicFeedLogging,
		arg.Account,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureCommunityAccount = `-- name: EnsureCommunityAccount :exec
INSERT INTO community_accounts(account) VALUES (?) ON CONFLICT(account) DO NOTHING
`

func (q *Queries) EnsureCommunityAccount(ctx context.Context, account string) error {
	_, err := q.db.ExecContext(ctx, ensureCommunityAccount, account)
	return err
}

const ensureCommunityConversation = `-- name: EnsureCommunityConversation :one
INSERT INTO community_conversations(account, kind, target) VALUES (?, ?, ?)
ON CONFLICT(account, kind, target) DO UPDATE SET target = excluded.target
RETURNING id, account, kind, target, read_through, closed
`

type EnsureCommunityConversationParams struct {
	Account string `json:"account"`
	Kind    string `json:"kind"`
	Target  string `json:"target"`
}

func (q *Queries) EnsureCommunityConversation(ctx context.Context, arg EnsureCommunityConversationParams) (CommunityConversation, error) {
	row := q.db.QueryRowContext(ctx, ensureCommunityConversation, arg.Account, arg.Kind, arg.Target)
	var i CommunityConversation
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Kind,
		&i.Target,
		&i.ReadThrough,
		&i.Closed,
	)
	return i, err
}

const exportCommunityMessages = `-- name: ExportCommunityMessages :many
SELECT id, account, conversation_id, sender, direction, body, created_at, server_time, state, mention, error FROM community_messages WHERE account = ? AND conversation_id = ? AND state <> 'held'
AND id > ?3 AND id <= ?4
AND instr(body, CAST(?5 AS TEXT)) > 0
ORDER BY id LIMIT min(max(CAST(?6 AS INTEGER), 1), 200)
`

type ExportCommunityMessagesParams struct {
	Account        string `json:"account"`
	ConversationID int64  `json:"conversation_id"`
	AfterID        int64  `json:"after_id"`
	ThroughID      int64  `json:"through_id"`
	SearchText     string `json:"search_text"`
	PageSize       int64  `json:"page_size"`
}

func (q *Queries) ExportCommunityMessages(ctx context.Context, arg ExportCommunityMessagesParams) ([]CommunityMessage, error) {
	rows, err := q.db.QueryContext(ctx, exportCommunityMessages,
		arg.Account,
		arg.ConversationID,
		arg.AfterID,
		arg.ThroughID,
		arg.SearchText,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityMessage
	for rows.Next() {
		var i CommunityMessage
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.ConversationID,
			&i.Sender,
			&i.Direction,
			&i.Body,
			&i.CreatedAt,
			&i.ServerTime,
			&i.State,
			&i.Mention,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCommunityConversation = `-- name: FindCommunityConversation :one
SELECT id, account, kind, target, read_through, closed FROM community_conversations WHERE account = ? AND kind = ? AND target = ?
`

type FindCommunityConversationParams struct {
	Account string `json:"account"`
	Kind    string `json:"kind"`
	Target  string `json:"target"`
}

func (q *Queries) FindCommunityConversation(ctx context.Context, arg FindCommunityConversationParams) (CommunityConversation, error) {
	row := q.db.QueryRowContext(ctx, findCommunityConversation, arg.Account, arg.Kind, arg.Target)
	var i CommunityConversation
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Kind,
		&i.Target,
		&i.ReadThrough,
		&i.Closed,
	)
	return i, err
}

const getCommunityAccount = `-- name: GetCommunityAccount :one
SELECT account, revision, description, accept_invitations, retention_days, public_feed_logging FROM community_accounts WHERE account = ?
`

func (q *Queries) GetCommunityAccount(ctx context.Context, account string) (CommunityAccount, error) {
	row := q.db.QueryRowContext(ctx, getCommunityAccount, account)
	var i CommunityAccount
	err := row.Scan(
		&i.Account,
		&i.Revision,
		&i.Description,
		&i.AcceptInvitations,
		&i.RetentionDays,
		&i.PublicFeedLogging,
	)
	return i, err
}

const getCommunityAlias = `-- name: GetCommunityAlias :one
SELECT account, name, expansion FROM community_aliases WHERE account = ? AND name = ?
`

type GetCommunityAliasParams struct {
	Account string `json:"account"`
	Name    string `json:"name"`
}

func (q *Queries) GetCommunityAlias(ctx context.Context, arg GetCommunityAliasParams) (CommunityAlias, error) {
	row := q.db.QueryRowContext(ctx, getCommunityAlias, arg.Account, arg.Name)
	var i CommunityAlias
	err := row.Scan(&i.Account, &i.Name, &i.Expansion)
	return i, err
}

const getCommunityBuddy = `-- name: GetCommunityBuddy :one
SELECT account, username, note, notify_online, priority, trusted, last_seen FROM community_buddies WHERE account = ? AND username = ?
`

type GetCommunityBuddyParams struct {
	Account  string `json:"account"`
	Username string `json:"username"`
}

func (q *Queries) GetCommunityBuddy(ctx context.Context, arg GetCommunityBuddyParams) (CommunityBuddy, error) {
	row := q.db.QueryRowContext(ctx, getCommunityBuddy, arg.Account, arg.Username)
	var i CommunityBuddy
	err := row.Scan(
		&i.Account,
		&i.Username,
		&i.Note,
		&i.NotifyOnline,
		&i.Priority,
		&i.Trusted,
		&i.LastSeen,
	)
	return i, err
}

const getCommunityConversation = `-- name: GetCommunityConversation :one
SELECT id, account, kind, target, read_through, closed FROM community_conversations WHERE account = ? AND id = ?
`

type GetCommunityConversationParams struct {
	Account string `json:"account"`
	ID      int64  `json:"id"`
}

func (q *Queries) GetCommunityConversation(ctx context.Context, arg GetCommunityConversationParams) (CommunityConversation, error) {
	row := q.db.QueryRowContext(ctx, getCommunityConversation, arg.Account, arg.ID)
	var i CommunityConversation
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Kind,
		&i.Target,
		&i.ReadThrough,
		&i.Closed,
	)
	return i, err
}

const getCommunityMessage = `-- name: GetCommunityMessage :one
SELECT id, account, conversation_id, sender, direction, body, created_at, server_time, state, mention, error FROM community_messages WHERE account = ? AND id = ?
`

type GetCommunityMessageParams struct {
	Account string `json:"account"`
	ID      int64  `json:"id"`
}

func (q *Queries) GetCommunityMessage(ctx context.Context, arg GetCommunityMessageParams) (CommunityMessage, error) {
	row := q.db.QueryRowContext(ctx, getCommunityMessage, arg.Account, arg.ID)
	var i CommunityMessage
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.ConversationID,
		&i.Sender,
		&i.Direction,
		&i.Body,
		&i.CreatedAt,
		&i.ServerTime,
		&i.State,
		&i.Mention,
		&i.Error,
	)
	return i, err
}

const getCommunityRoom = `-- name: GetCommunityRoom :one
SELECT account, room, autojoin, private_room, own_wall FROM community_rooms WHERE account = ? AND room = ?
`

type GetCommunityRoomParams struct {
	Account string `json:"account"`
	Room    string `json:"room"`
}

func (q *Queries) GetCommunityRoom(ctx context.Context, arg GetCommunityRoomParams) (CommunityRoom, error) {
	row := q.db.QueryRowContext(ctx, getCommunityRoom, arg.Account, arg.Room)
	var i CommunityRoom
	err := row.Scan(
		&i.Account,
		&i.Room,
		&i.Autojoin,
		&i.PrivateRoom,
		&i.OwnWall,
	)
	return i, err
}

const getCommunitySubmission = `-- name: GetCommunitySubmission :one
SELECT account, request_id, kind, fingerprint, result, created_at FROM community_submissions WHERE account = ? AND request_id = ?
`

type GetCommunitySubmissionParams struct {
	Account   string `json:"account"`
	RequestID string `json:"request_id"`
}

func (q *Queries) GetCommunitySubmission(ctx context.Context, arg GetCommunitySubmissionParams) (CommunitySubmission, error) {
	row := q.db.QueryRowContext(ctx, getCommunitySubmission, arg.Account, arg.RequestID)
	var i CommunitySubmission
	err := row.Scan(
		&i.Account,
		&i.RequestID,
		&i.Kind,
		&i.Fingerprint,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const insertCommunityMessage = `-- name: InsertCommunityMessage :one
INSERT INTO community_messages(account, conversation_id, sender, direction, body, created_at, server_time, state, mention)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, account, conversation_id, sender, direction, body, created_at, server_time, state, mention, error
`

type InsertCommunityMessageParams struct {
	Account        string `json:"account"`
	ConversationID int64  `json:"conversation_id"`
	Sender         string `json:"sender"`
	Direction      string `json:"direction"`
	Body           string `json:"body"`
	CreatedAt      int64  `json:"created_at"`
	ServerTime     *int64 `json:"server_time"`
	State          string `json:"state"`
	Mention        int64  `json:"mention"`
}

func (q *Queries) InsertCommunityMessage(ctx context.Context, arg InsertCommunityMessageParams) (CommunityMessage, error) {
	row := q.db.QueryRowContext(ctx, insertCommunityMessage,
		arg.Account,
		arg.ConversationID,
		arg.Sender,
		arg.Direction,
		arg.Body,
		arg.CreatedAt,
		arg.ServerTime,
		arg.State,
		arg.Mention,
	)
	var i CommunityMessage
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.ConversationID,
		&i.Sender,
		&i.Direction,
		&i.Body,
		&i.CreatedAt,
		&i.ServerTime,
		&i.State,
		&i.Mention,
		&i.Error,
	)
	return i, err
}

const insertCommunityReceipt = `-- name: InsertCommunityReceipt :execrows
INSERT INTO community_receipts(account, sender, server_id, server_time, fingerprint, disposition, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(account, sender, server_id, server_time, fingerprint) DO NOTHING
`

type InsertCommunityReceiptParams struct {
	Account     string `json:"account"`
	Sender      string `json:"sender"`
	ServerID    int64  `json:"server_id"`
	ServerTime  int64  `json:"server_time"`
	Fingerprint []byte `json:"fingerprint"`
	Disposition string `json:"disposition"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) InsertCommunityReceipt(ctx context.Context, arg InsertCommunityReceiptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCommunityReceipt,
		arg.Account,
		arg.Sender,
		arg.ServerID,
		arg.ServerTime,
		arg.Fingerprint,
		arg.Disposition,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertCommunitySubmission = `-- name: InsertCommunitySubmission :execrows
INSERT INTO community_submissions(account, request_id, kind, fingerprint, result, created_at) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(account, request_id) DO NOTHING
`

type InsertCommunitySubmissionParams struct {
	Account     string `json:"account"`
	RequestID   string `json:"request_id"`
	Kind        string `json:"kind"`
	Fingerprint []byte `json:"fingerprint"`
	Result      string `json:"result"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) InsertCommunitySubmission(ctx context.Context, arg InsertCommunitySubmissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertCommunitySubmission,
		arg.Account,
		arg.RequestID,
		arg.Kind,
		arg.Fingerprint,
		arg.Result,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listCommunityAliases = `-- name: ListCommunityAliases :many
SELECT account, name, expansion FROM community_aliases WHERE account = ? AND name > ?2
ORDER BY name LIMIT min(max(CAST(?3 AS INTEGER), 1), 200)
`

type ListCommunityAliasesParams struct {
	Account   string `json:"account"`
	AfterName string `json:"after_name"`
	PageSize  int64  `json:"page_size"`
}

func (q *Queries) ListCommunityAliases(ctx context.Context, arg ListCommunityAliasesParams) ([]CommunityAlias, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityAliases, arg.Account, arg.AfterName, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityAlias
	for rows.Next() {
		var i CommunityAlias
		if err := rows.Scan(&i.Account, &i.Name, &i.Expansion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityBuddies = `-- name: ListCommunityBuddies :many
SELECT account, username, note, notify_online, priority, trusted, last_seen FROM community_buddies WHERE account = ? AND username > ?2
ORDER BY username LIMIT min(max(CAST(?3 AS INTEGER), 1), 200)
`

type ListCommunityBuddiesParams struct {
	Account       string `json:"account"`
	AfterUsername string `json:"after_username"`
	PageSize      int64  `json:"page_size"`
}

func (q *Queries) ListCommunityBuddies(ctx context.Context, arg ListCommunityBuddiesParams) ([]CommunityBuddy, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityBuddies, arg.Account, arg.AfterUsername, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityBuddy
	for rows.Next() {
		var i CommunityBuddy
		if err := rows.Scan(
			&i.Account,
			&i.Username,
			&i.Note,
			&i.NotifyOnline,
			&i.Priority,
			&i.Trusted,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityConversations = `-- name: ListCommunityConversations :many
SELECT id, account, kind, target, read_through, closed FROM community_conversations WHERE account = ? AND id > ?2
ORDER BY id LIMIT min(max(CAST(?3 AS INTEGER), 1), 200)
`

type ListCommunityConversationsParams struct {
	Account  string `json:"account"`
	AfterID  int64  `json:"after_id"`
	PageSize int64  `json:"page_size"`
}

func (q *Queries) ListCommunityConversations(ctx context.Context, arg ListCommunityConversationsParams) ([]CommunityConversation, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityConversations, arg.Account, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityConversation
	for rows.Next() {
		var i CommunityConversation
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Kind,
			&i.Target,
			&i.ReadThrough,
			&i.Closed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityInterests = `-- name: ListCommunityInterests :many
SELECT account, item, opinion FROM community_interests WHERE account = ? AND item > ?2
ORDER BY item LIMIT min(max(CAST(?3 AS INTEGER), 1), 200)
`

type ListCommunityInterestsParams struct {
	Account   string `json:"account"`
	AfterItem string `json:"after_item"`
	PageSize  int64  `json:"page_size"`
}

func (q *Queries) ListCommunityInterests(ctx context.Context, arg ListCommunityInterestsParams) ([]CommunityInterest, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityInterests, arg.Account, arg.AfterItem, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityInterest
	for rows.Next() {
		var i CommunityInterest
		if err := rows.Scan(&i.Account, &i.Item, &i.Opinion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityMessages = `-- name: ListCommunityMessages :many
SELECT id, account, conversation_id, sender, direction, body, created_at, server_time, state, mention, error FROM community_messages WHERE account = ? AND conversation_id = ? AND state <> 'held'
AND (CAST(?3 AS INTEGER) = 0 OR id < ?3) AND instr(body, CAST(?4 AS TEXT)) > 0
ORDER BY id DESC LIMIT min(max(CAST(?5 AS INTEGER), 1), 200)
`

type ListCommunityMessagesParams struct {
	Account        string `json:"account"`
	ConversationID int64  `json:"conversation_id"`
	BeforeID       int64  `json:"before_id"`
	SearchText     string `json:"search_text"`
	PageSize       int64  `json:"page_size"`
}

func (q *Queries) ListCommunityMessages(ctx context.Context, arg ListCommunityMessagesParams) ([]CommunityMessage, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityMessages,
		arg.Account,
		arg.ConversationID,
		arg.BeforeID,
		arg.SearchText,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityMessage
	for rows.Next() {
		var i CommunityMessage
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.ConversationID,
			&i.Sender,
			&i.Direction,
			&i.Body,
			&i.CreatedAt,
			&i.ServerTime,
			&i.State,
			&i.Mention,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityOutbox = `-- name: ListCommunityOutbox :many
SELECT id, account, conversation_id, sender, direction, body, created_at, server_time, state, mention, error FROM community_messages WHERE account = ? AND direction = 'outgoing' AND state = 'queued' AND id > ?2
ORDER BY id LIMIT min(max(CAST(?3 AS INTEGER), 1), 200)
`

type ListCommunityOutboxParams struct {
	Account  string `json:"account"`
	AfterID  int64  `json:"after_id"`
	PageSize int64  `json:"page_size"`
}

func (q *Queries) ListCommunityOutbox(ctx context.Context, arg ListCommunityOutboxParams) ([]CommunityMessage, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityOutbox, arg.Account, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityMessage
	for rows.Next() {
		var i CommunityMessage
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.ConversationID,
			&i.Sender,
			&i.Direction,
			&i.Body,
			&i.CreatedAt,
			&i.ServerTime,
			&i.State,
			&i.Mention,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityRooms = `-- name: ListCommunityRooms :many
SELECT account, room, autojoin, private_room, own_wall FROM community_rooms WHERE account = ? AND room > ?2
ORDER BY room LIMIT min(max(CAST(?3 AS INTEGER), 1), 200)
`

type ListCommunityRoomsParams struct {
	Account   string `json:"account"`
	AfterRoom string `json:"after_room"`
	PageSize  int64  `json:"page_size"`
}

func (q *Queries) ListCommunityRooms(ctx context.Context, arg ListCommunityRoomsParams) ([]CommunityRoom, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityRooms, arg.Account, arg.AfterRoom, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityRoom
	for rows.Next() {
		var i CommunityRoom
		if err := rows.Scan(
			&i.Account,
			&i.Room,
			&i.Autojoin,
			&i.PrivateRoom,
			&i.OwnWall,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityRules = `-- name: ListCommunityRules :many
SELECT id, account, "action", kind, value, message FROM community_rules WHERE account = ? AND id > ?2
ORDER BY id LIMIT min(max(CAST(?3 AS INTEGER), 1), 200)
`

type ListCommunityRulesParams struct {
	Account  string `json:"account"`
	AfterID  int64  `json:"after_id"`
	PageSize int64  `json:"page_size"`
}

func (q *Queries) ListCommunityRules(ctx context.Context, arg ListCommunityRulesParams) ([]CommunityRule, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityRules, arg.Account, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityRule
	for rows.Next() {
		var i CommunityRule
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Action,
			&i.Kind,
			&i.Value,
			&i.Message,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeldCommunityMessages = `-- name: ListHeldCommunityMessages :many
SELECT id, account, conversation_id, sender, direction, body, created_at, server_time, state, mention, error FROM community_messages WHERE account = ? AND sender = ? AND state = 'held' AND id > ?3
ORDER BY id LIMIT min(max(CAST(?4 AS INTEGER), 1), 200)
`

type ListHeldCommunityMessagesParams struct {
	Account  string `json:"account"`
	Sender   string `json:"sender"`
	AfterID  int64  `json:"after_id"`
	PageSize int64  `json:"page_size"`
}

func (q *Queries) ListHeldCommunityMessages(ctx context.Context, arg ListHeldCommunityMessagesParams) ([]CommunityMessage, error) {
	rows, err := q.db.QueryContext(ctx, listHeldCommunityMessages,
		arg.Account,
		arg.Sender,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityMessage
	for rows.Next() {
		var i CommunityMessage
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.ConversationID,
			&i.Sender,
			&i.Direction,
			&i.Body,
			&i.CreatedAt,
			&i.ServerTime,
			&i.State,
			&i.Mention,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCommunityRead = `-- name: MarkCommunityRead :execrows
UPDATE community_conversations SET read_through = max(community_conversations.read_through, CAST(?1 AS INTEGER))
WHERE community_conversations.account = ?2 AND community_conversations.id = ?3
AND (?1 <= community_conversations.read_through OR EXISTS (
    SELECT 1 FROM community_messages m WHERE m.account = ?2
    AND m.conversation_id = ?3 AND m.id = ?1 AND m.state <> 'held'
))
`

type MarkCommunityReadParams struct {
	ThroughID      int64  `json:"through_id"`
	Account        string `json:"account"`
	ConversationID int64  `json:"conversation_id"`
}

func (q *Queries) MarkCommunityRead(ctx context.Context, arg MarkCommunityReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCommunityRead, arg.ThroughID, arg.Account, arg.ConversationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const nextHeldCommunitySender = `-- name: NextHeldCommunitySender :one
SELECT sender FROM community_messages WHERE account = ? AND state = 'held' AND sender > ?2
GROUP BY sender ORDER BY sender LIMIT 1
`

type NextHeldCommunitySenderParams struct {
	Account     string `json:"account"`
	AfterSender string `json:"after_sender"`
}

func (q *Queries) NextHeldCommunitySender(ctx context.Context, arg NextHeldCommunitySenderParams) (string, error) {
	row := q.db.QueryRowContext(ctx, nextHeldCommunitySender, arg.Account, arg.AfterSender)
	var sender string
	err := row.Scan(&sender)
	return sender, err
}

const pageCommunityConversations = `-- name: PageCommunityConversations :many
SELECT c.id, c.account, c.kind, c.target, c.read_through, c.closed,
    (SELECT count(*) FROM community_messages m WHERE m.account = c.account AND m.conversation_id = c.id AND m.id > c.read_through AND m.direction = 'incoming' AND m.state = 'received') AS unread,
    (SELECT CAST(coalesce(sum(m.mention), 0) AS INTEGER) FROM community_messages m WHERE m.account = c.account AND m.conversation_id = c.id AND m.id > c.read_through AND m.direction = 'incoming' AND m.state = 'received') AS mentions,
    (SELECT CAST(coalesce(max(m.id), 0) AS INTEGER) FROM community_messages m WHERE m.account = c.account AND m.conversation_id = c.id AND m.state <> 'held') AS latest_id
FROM community_conversations c WHERE c.account = ?1 AND c.id > ?2
AND (CAST(?3 AS TEXT) = '' OR c.kind = ?3)
AND (CAST(?4 AS INTEGER) <> 0 OR c.closed = 0)
AND instr(c.target, CAST(?5 AS TEXT)) > 0
ORDER BY c.id LIMIT min(max(CAST(?6 AS INTEGER), 1), 200)
`

type PageCommunityConversationsParams struct {
	Account       string `json:"account"`
	AfterID       int64  `json:"after_id"`
	Kind          string `json:"kind"`
	IncludeClosed int64  `json:"include_closed"`
	SearchText    string `json:"search_text"`
	PageSize      int64  `json:"page_size"`
}

type PageCommunityConversationsRow struct {
	ID          int64  `json:"id"`
	Account     string `json:"account"`
	Kind        string `json:"kind"`
	Target      string `json:"target"`
	ReadThrough int64  `json:"read_through"`
	Closed      int64  `json:"closed"`
	Unread      int64  `json:"unread"`
	Mentions    int64  `json:"mentions"`
	LatestID    int64  `json:"latest_id"`
}

func (q *Queries) PageCommunityConversations(ctx context.Context, arg PageCommunityConversationsParams) ([]PageCommunityConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, pageCommunityConversations,
		arg.Account,
		arg.AfterID,
		arg.Kind,
		arg.IncludeClosed,
		arg.SearchText,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageCommunityConversationsRow
	for rows.Next() {
		var i PageCommunityConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Kind,
			&i.Target,
			&i.ReadThrough,
			&i.Closed,
			&i.Unread,
			&i.Mentions,
			&i.LatestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putCommunityAlias = `-- name: PutCommunityAlias :exec
INSERT INTO community_aliases(account, name, expansion) VALUES (?, ?, ?)
ON CONFLICT(account, name) DO UPDATE SET expansion = excluded.expansion
`

type PutCommunityAliasParams struct {
	Account   string `json:"account"`
	Name      string `json:"name"`
	Expansion string `json:"expansion"`
}

func (q *Queries) PutCommunityAlias(ctx context.Context, arg PutCommunityAliasParams) error {
	_, err := q.db.ExecContext(ctx, putCommunityAlias, arg.Account, arg.Name, arg.Expansion)
	return err
}

const putCommunityBuddy = `-- name: PutCommunityBuddy :exec
INSERT INTO community_buddies(account, username, note, notify_online, priority, trusted) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(account, username) DO UPDATE SET note = excluded.note, notify_online = excluded.notify_online, priority = excluded.priority, trusted = excluded.trusted
`

type PutCommunityBuddyParams struct {
	Account      string `json:"account"`
	Username     string `json:"username"`
	Note         string `json:"note"`
	NotifyOnline int64  `json:"notify_online"`
	Priority     int64  `json:"priority"`
	Trusted      int64  `json:"trusted"`
}

func (q *Queries) PutCommunityBuddy(ctx context.Context, arg PutCommunityBuddyParams) error {
	_, err := q.db.ExecContext(ctx, putCommunityBuddy,
		arg.Account,
		arg.Username,
		arg.Note,
		arg.NotifyOnline,
		arg.Priority,
		arg.Trusted,
	)
	return err
}

const putCommunityInterest = `-- name: PutCommunityInterest :exec
INSERT INTO community_interests(account, item, opinion) VALUES (?, ?, ?)
ON CONFLICT(account, item) DO UPDATE SET opinion = excluded.opinion
`

type PutCommunityInterestParams struct {
	Account string `json:"account"`
	Item    string `json:"item"`
	Opinion int64  `json:"opinion"`
}

func (q *Queries) PutCommunityInterest(ctx context.Context, arg PutCommunityInterestParams) error {
	_, err := q.db.ExecContext(ctx, putCommunityInterest, arg.Account, arg.Item, arg.Opinion)
	return err
}

const putCommunityRoom = `-- name: PutCommunityRoom :exec
INSERT INTO community_rooms(account, room, autojoin, private_room, own_wall) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(account, room) DO UPDATE SET autojoin = excluded.autojoin, private_room = excluded.private_room, own_wall = excluded.own_wall
`

type PutCommunityRoomParams struct {
	Account     string `json:"account"`
	Room        string `json:"room"`
	Autojoin    int64  `json:"autojoin"`
	PrivateRoom int64  `json:"private_room"`
	OwnWall     string `json:"own_wall"`
}

func (q *Queries) PutCommunityRoom(ctx context.Context, arg PutCommunityRoomParams) error {
	_, err := q.db.ExecContext(ctx, putCommunityRoom,
		arg.Account,
		arg.Room,
		arg.Autojoin,
		arg.PrivateRoom,
		arg.OwnWall,
	)
	return err
}

const putCommunityRule = `-- name: PutCommunityRule :one
INSERT INTO community_rules(account, action, kind, value, message) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(account, action, kind, value) DO UPDATE SET message = excluded.message RETURNING id, account, "action", kind, value, message
`

type PutCommunityRuleParams struct {
	Account string `json:"account"`
	Action  string `json:"action"`
	Kind    string `json:"kind"`
	Value   string `json:"value"`
	Message string `json:"message"`
}

func (q *Queries) PutCommunityRule(ctx context.Context, arg PutCommunityRuleParams) (CommunityRule, error) {
	row := q.db.QueryRowContext(ctx, putCommunityRule,
		arg.Account,
		arg.Action,
		arg.Kind,
		arg.Value,
		arg.Message,
	)
	var i CommunityRule
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Action,
		&i.Kind,
		&i.Value,
		&i.Message,
	)
	return i, err
}

const recoverCommunityOutbox = `-- name: RecoverCommunityOutbox :execrows
UPDATE community_messages SET state = 'unknown' WHERE (CAST(?1 AS TEXT) = '' OR account = ?1) AND direction = 'outgoing' AND state = 'sending'
`

func (q *Queries) RecoverCommunityOutbox(ctx context.Context, account string) (int64, error) {
	result, err := q.db.ExecContext(ctx, recoverCommunityOutbox, account)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveHeldCommunityReceipts = `-- name: ResolveHeldCommunityReceipts :execrows
UPDATE community_receipts SET disposition = ? WHERE account = ? AND sender = ? AND disposition = 'held'
`

type ResolveHeldCommunityReceiptsParams struct {
	Disposition string `json:"disposition"`
	Account     string `json:"account"`
	Sender      string `json:"sender"`
}

func (q *Queries) ResolveHeldCommunityReceipts(ctx context.Context, arg ResolveHeldCommunityReceiptsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveHeldCommunityReceipts, arg.Disposition, arg.Account, arg.Sender)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCommunityBuddyLastSeen = `-- name: SetCommunityBuddyLastSeen :exec
UPDATE community_buddies SET last_seen = max(coalesce(last_seen, 0), CAST(?1 AS INTEGER))
WHERE account = ?2 AND username = ?3
`

type SetCommunityBuddyLastSeenParams struct {
	SeenAt   int64  `json:"seen_at"`
	Account  string `json:"account"`
	Username string `json:"username"`
}

func (q *Queries) SetCommunityBuddyLastSeen(ctx context.Context, arg SetCommunityBuddyLastSeenParams) error {
	_, err := q.db.ExecContext(ctx, setCommunityBuddyLastSeen, arg.SeenAt, arg.Account, arg.Username)
	return err
}

const setCommunityConversationClosed = `-- name: SetCommunityConversationClosed :execrows
UPDATE community_conversations SET closed = ? WHERE account = ? AND id = ?
`

type SetCommunityConversationClosedParams struct {
	Closed  int64  `json:"closed"`
	Account string `json:"account"`
	ID      int64  `json:"id"`
}

func (q *Queries) SetCommunityConversationClosed(ctx context.Context, arg SetCommunityConversationClosedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCommunityConversationClosed, arg.Closed, arg.Account, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCommunityMessageState = `-- name: SetCommunityMessageState :execrows
UPDATE community_messages SET state = ?1, error = ?2
WHERE account = ?3 AND id = ?4 AND state = ?5
`

type SetCommunityMessageStateParams struct {
	NewState string `json:"new_state"`
	Error    string `json:"error"`
	Account  string `json:"account"`
	ID       int64  `json:"id"`
	OldState string `json:"old_state"`
}

func (q *Queries) SetCommunityMessageState(ctx context.Context, arg SetCommunityMessageStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCommunityMessageState,
		arg.NewState,
		arg.Error,
		arg.Account,
		arg.ID,
		arg.OldState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCommunitySubmissionResult = `-- name: SetCommunitySubmissionResult :execrows
UPDATE community_submissions SET result = ? WHERE account = ? AND request_id = ?
`

type SetCommunitySubmissionResultParams struct {
	Result    string `json:"result"`
	Account   string `json:"account"`
	RequestID string `json:"request_id"`
}

func (q *Queries) SetCommunitySubmissionResult(ctx context.Context, arg SetCommunitySubmissionResultParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCommunitySubmissionResult, arg.Result, arg.Account, arg.RequestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCommunityRule = `-- name: UpdateCommunityRule :one
UPDATE community_rules SET action = ?, kind = ?, value = ?, message = ? WHERE account = ? AND id = ? RETURNING id, account, "action", kind, value, message
`

type UpdateCommunityRuleParams struct {
	Action  string `json:"action"`
	Kind    string `json:"kind"`
	Value   string `json:"value"`
	Message string `json:"message"`
	Account string `json:"account"`
	ID      int64  `json:"id"`
}

func (q *Queries) UpdateCommunityRule(ctx context.Context, arg UpdateCommunityRuleParams) (CommunityRule, error) {
	row := q.db.QueryRowContext(ctx, updateCommunityRule,
		arg.Action,
		arg.Kind,
		arg.Value,
		arg.Message,
		arg.Account,
		arg.ID,
	)
	var i CommunityRule
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Action,
		&i.Kind,
		&i.Value,
		&i.Message,
	)
	return i, err
}
