// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type ActiveAttempt struct {
	ID         string `json:"id"`
	TransferID string `json:"transfer_id"`
	Attempt    []byte `json:"attempt"`
	Direction  string `json:"direction"`
	Username   string `json:"username"`
	Filename   string `json:"filename"`
	EventID    string `json:"event_id"`
	Payload    []byte `json:"payload"`
}

type CommunityAccount struct {
	Account           string `json:"account"`
	Revision          int64  `json:"revision"`
	Description       string `json:"description"`
	AcceptInvitations int64  `json:"accept_invitations"`
	RetentionDays     int64  `json:"retention_days"`
	PublicFeedLogging int64  `json:"public_feed_logging"`
}

type CommunityAlias struct {
	Account   string `json:"account"`
	Name      string `json:"name"`
	Expansion string `json:"expansion"`
}

type CommunityBuddy struct {
	Account      string `json:"account"`
	Username     string `json:"username"`
	Note         string `json:"note"`
	NotifyOnline int64  `json:"notify_online"`
	Priority     int64  `json:"priority"`
	Trusted      int64  `json:"trusted"`
	LastSeen     *int64 `json:"last_seen"`
}

type CommunityConversation struct {
	ID          int64  `json:"id"`
	Account     string `json:"account"`
	Kind        string `json:"kind"`
	Target      string `json:"target"`
	ReadThrough int64  `json:"read_through"`
	Closed      int64  `json:"closed"`
}

type CommunityInterest struct {
	Account string `json:"account"`
	Item    string `json:"item"`
	Opinion int64  `json:"opinion"`
}

type CommunityMessage struct {
	ID             int64  `json:"id"`
	Account        string `json:"account"`
	ConversationID int64  `json:"conversation_id"`
	Sender         string `json:"sender"`
	Direction      string `json:"direction"`
	Body           string `json:"body"`
	CreatedAt      int64  `json:"created_at"`
	ServerTime     *int64 `json:"server_time"`
	State          string `json:"state"`
	Mention        int64  `json:"mention"`
	Error          string `json:"error"`
}

type CommunityReceipt struct {
	Account     string `json:"account"`
	Sender      string `json:"sender"`
	ServerID    int64  `json:"server_id"`
	ServerTime  int64  `json:"server_time"`
	Fingerprint []byte `json:"fingerprint"`
	Disposition string `json:"disposition"`
	CreatedAt   int64  `json:"created_at"`
}

type CommunityRoom struct {
	Account     string `json:"account"`
	Room        string `json:"room"`
	Autojoin    int64  `json:"autojoin"`
	PrivateRoom int64  `json:"private_room"`
	OwnWall     string `json:"own_wall"`
}

type CommunityRule struct {
	ID      int64  `json:"id"`
	Account string `json:"account"`
	Action  string `json:"action"`
	Kind    string `json:"kind"`
	Value   string `json:"value"`
	Message string `json:"message"`
}

type CommunitySubmission struct {
	Account     string `json:"account"`
	RequestID   string `json:"request_id"`
	Kind        string `json:"kind"`
	Fingerprint []byte `json:"fingerprint"`
	Result      string `json:"result"`
	CreatedAt   int64  `json:"created_at"`
}

type Download struct {
	ID           string `json:"id"`
	StatsAccount string `json:"stats_account"`
	FilterBypass int64  `json:"filter_bypass"`
	Username     string `json:"username"`
	Filename     string `json:"filename"`
	Size         []byte `json:"size"`
	Offset       []byte `json:"offset"`
	DownloadDir  string `json:"download_dir"`
	Destination  string `json:"destination"`
	State        string `json:"state"`
	RetryAt      *int64 `json:"retry_at"`
	Error        string `json:"error"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type Event struct {
	ID        string  `json:"id"`
	Account   *string `json:"account"`
	Peer      *string `json:"peer"`
	Direction *string `json:"direction"`
	Session   *string `json:"session"`
	Kind      *string `json:"kind"`
	At        *int64  `json:"at"`
	Data      string  `json:"data"`
}

type History struct {
	Kind    string `json:"kind"`
	Value   string `json:"value"`
	Recency []byte `json:"recency"`
}

type Seen struct {
	ID string `json:"id"`
}

type ShareEntry struct {
	SnapshotID       int64  `json:"snapshot_id"`
	Ordinal          int64  `json:"ordinal"`
	Kind             string `json:"kind"`
	Root             string `json:"root"`
	Path             string `json:"path"`
	Name             string `json:"name"`
	Size             []byte `json:"size"`
	Directory        int64  `json:"directory"`
	Private          int64  `json:"private"`
	Vbr              int64  `json:"vbr"`
	VbrKnown         int64  `json:"vbr_known"`
	Extension        string `json:"extension"`
	Bitrate          int64  `json:"bitrate"`
	Duration         int64  `json:"duration"`
	SampleRate       int64  `json:"sample_rate"`
	BitDepth         int64  `json:"bit_depth"`
	AudioSource      string `json:"audio_source"`
	FingerprintSize  []byte `json:"fingerprint_size"`
	FingerprintMtime int64  `json:"fingerprint_mtime"`
	FingerprintCtime int64  `json:"fingerprint_ctime"`
	ExtractorVersion string `json:"extractor_version"`
}

type ShareExclusion struct {
	SnapshotID int64  `json:"snapshot_id"`
	Ordinal    int64  `json:"ordinal"`
	Pattern    string `json:"pattern"`
}

type ShareHead struct {
	Source             string `json:"source"`
	NormalizedUsername string `json:"normalized_username"`
	SnapshotID         int64  `json:"snapshot_id"`
}

type ShareRoot struct {
	SnapshotID int64  `json:"snapshot_id"`
	Ordinal    int64  `json:"ordinal"`
	Name       string `json:"name"`
	Path       string `json:"path"`
	Access     string `json:"access"`
}

type ShareSnapshot struct {
	ID                 int64  `json:"id"`
	Source             string `json:"source"`
	NormalizedUsername string `json:"normalized_username"`
	Username           string `json:"username"`
	SavedAt            int64  `json:"saved_at"`
	State              string `json:"state"`
	CreatedAt          int64  `json:"created_at"`
}

type StateMetum struct {
	ID                  int64  `json:"id"`
	DownloadSequence    []byte `json:"download_sequence"`
	UploadSequence      []byte `json:"upload_sequence"`
	UploadQueueSequence []byte `json:"upload_queue_sequence"`
	WishlistSequence    []byte `json:"wishlist_sequence"`
	HistorySequence     []byte `json:"history_sequence"`
	StatsSince          *int64 `json:"stats_since"`
}

type StorageSchema struct {
	ID      int64 `json:"id"`
	Version int64 `json:"version"`
}

type Total struct {
	Account   *string `json:"account"`
	Peer      *string `json:"peer"`
	Direction *string `json:"direction"`
	Session   *string `json:"session"`
	Day       *string `json:"day"`
	Data      string  `json:"data"`
}

type UiPreference struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Upload struct {
	ID          string `json:"id"`
	Account     string `json:"account"`
	Username    string `json:"username"`
	Filename    string `json:"filename"`
	Direction   string `json:"direction"`
	State       string `json:"state"`
	Done        []byte `json:"done"`
	Total       []byte `json:"total"`
	ElapsedMs   []byte `json:"elapsed_ms"`
	SpeedBps    []byte `json:"speed_bps"`
	EtaSeconds  []byte `json:"eta_seconds"`
	Queue       int64  `json:"queue"`
	Error       string `json:"error"`
	QueueOrder  []byte `json:"queue_order"`
	Fingerprint string `json:"fingerprint"`
	CreatedAt   int64  `json:"created_at"`
	QueuedAt    int64  `json:"queued_at"`
	UpdatedAt   int64  `json:"updated_at"`
	Recoverable int64  `json:"recoverable"`
}

type Wishlist struct {
	ID                   string `json:"id"`
	Query                string `json:"query"`
	Filter               string `json:"filter"`
	AddedAt              int64  `json:"added_at"`
	LastRunAt            *int64 `json:"last_run_at"`
	ResultCount          int64  `json:"result_count"`
	ResultSignature      string `json:"result_signature"`
	Unread               int64  `json:"unread"`
	NotificationSequence []byte `json:"notification_sequence"`
}
