// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package db

import (
	"context"
	"database/sql"
)

const countShareEntries = `-- name: CountShareEntries :one
SELECT count(*) FROM share_entries WHERE snapshot_id = ?
`

func (q *Queries) CountShareEntries(ctx context.Context, snapshotID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countShareEntries, snapshotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShareExclusions = `-- name: CountShareExclusions :one
SELECT count(*) FROM share_exclusions WHERE snapshot_id = ?
`

func (q *Queries) CountShareExclusions(ctx context.Context, snapshotID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countShareExclusions, snapshotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShareRoots = `-- name: CountShareRoots :one
SELECT count(*) FROM share_roots WHERE snapshot_id = ?
`

func (q *Queries) CountShareRoots(ctx context.Context, snapshotID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countShareRoots, snapshotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShareSnapshot = `-- name: CreateShareSnapshot :one
INSERT INTO share_snapshots(source, normalized_username, username, saved_at, state, created_at)
VALUES (?, ?, ?, ?, 'staging', ?) RETURNING id
`

type CreateShareSnapshotParams struct {
	Source             string `json:"source"`
	NormalizedUsername string `json:"normalized_username"`
	Username           string `json:"username"`
	SavedAt            int64  `json:"saved_at"`
	CreatedAt          int64  `json:"created_at"`
}

func (q *Queries) CreateShareSnapshot(ctx context.Context, arg CreateShareSnapshotParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createShareSnapshot,
		arg.Source,
		arg.NormalizedUsername,
		arg.Username,
		arg.SavedAt,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteShareEntriesBatch = `-- name: DeleteShareEntriesBatch :exec
DELETE FROM share_entries
WHERE rowid IN (SELECT e.rowid FROM share_entries AS e WHERE e.snapshot_id = ? LIMIT ?)
`

type DeleteShareEntriesBatchParams struct {
	SnapshotID int64 `json:"snapshot_id"`
	Limit      int64 `json:"limit"`
}

func (q *Queries) DeleteShareEntriesBatch(ctx context.Context, arg DeleteShareEntriesBatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteShareEntriesBatch, arg.SnapshotID, arg.Limit)
	return err
}

const deleteShareExclusionsBatch = `-- name: DeleteShareExclusionsBatch :exec
DELETE FROM share_exclusions
WHERE rowid IN (SELECT e.rowid FROM share_exclusions AS e WHERE e.snapshot_id = ? LIMIT ?)
`

type DeleteShareExclusionsBatchParams struct {
	SnapshotID int64 `json:"snapshot_id"`
	Limit      int64 `json:"limit"`
}

func (q *Queries) DeleteShareExclusionsBatch(ctx context.Context, arg DeleteShareExclusionsBatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteShareExclusionsBatch, arg.SnapshotID, arg.Limit)
	return err
}

const deleteShareRootsBatch = `-- name: DeleteShareRootsBatch :exec
DELETE FROM share_roots
WHERE rowid IN (SELECT r.rowid FROM share_roots AS r WHERE r.snapshot_id = ? LIMIT ?)
`

type DeleteShareRootsBatchParams struct {
	SnapshotID int64 `json:"snapshot_id"`
	Limit      int64 `json:"limit"`
}

func (q *Queries) DeleteShareRootsBatch(ctx context.Context, arg DeleteShareRootsBatchParams) error {
	_, err := q.db.ExecContext(ctx, deleteShareRootsBatch, arg.SnapshotID, arg.Limit)
	return err
}

const deleteShareSnapshot = `-- name: DeleteShareSnapshot :exec
DELETE FROM share_snapshots WHERE id = ? AND state <> 'staging'
  AND NOT EXISTS (SELECT 1 FROM share_heads WHERE snapshot_id = share_snapshots.id)
`

func (q *Queries) DeleteShareSnapshot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteShareSnapshot, id)
	return err
}

const deleteStagingShareSnapshot = `-- name: DeleteStagingShareSnapshot :exec
DELETE FROM share_snapshots WHERE id = ? AND state = 'staging'
  AND NOT EXISTS (SELECT 1 FROM share_heads WHERE snapshot_id = share_snapshots.id)
`

func (q *Queries) DeleteStagingShareSnapshot(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStagingShareSnapshot, id)
	return err
}

const getShareHead = `-- name: GetShareHead :one
SELECT source, normalized_username, snapshot_id FROM share_heads
WHERE source = ? AND normalized_username = ?
`

type GetShareHeadParams struct {
	Source             string `json:"source"`
	NormalizedUsername string `json:"normalized_username"`
}

func (q *Queries) GetShareHead(ctx context.Context, arg GetShareHeadParams) (ShareHead, error) {
	row := q.db.QueryRowContext(ctx, getShareHead, arg.Source, arg.NormalizedUsername)
	var i ShareHead
	err := row.Scan(&i.Source, &i.NormalizedUsername, &i.SnapshotID)
	return i, err
}

const getShareSnapshot = `-- name: GetShareSnapshot :one
SELECT id, source, normalized_username, username, saved_at, state, created_at
FROM share_snapshots WHERE id = ?
`

func (q *Queries) GetShareSnapshot(ctx context.Context, id int64) (ShareSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getShareSnapshot, id)
	var i ShareSnapshot
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.NormalizedUsername,
		&i.Username,
		&i.SavedAt,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const insertShareEntries = `-- name: InsertShareEntries :many
INSERT INTO share_entries (snapshot_id, ordinal, kind, root, path, name, size, directory, private, vbr, vbr_known, extension, bitrate, duration, sample_rate, bit_depth, audio_source, fingerprint_size, fingerprint_mtime, fingerprint_ctime, extractor_version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING ordinal
`

type InsertShareEntriesParams struct {
	SnapshotID       int64  `json:"snapshot_id"`
	Ordinal          int64  `json:"ordinal"`
	Kind             string `json:"kind"`
	Root             string `json:"root"`
	Path             string `json:"path"`
	Name             string `json:"name"`
	Size             []byte `json:"size"`
	Directory        int64  `json:"directory"`
	Private          int64  `json:"private"`
	Vbr              int64  `json:"vbr"`
	VbrKnown         int64  `json:"vbr_known"`
	Extension        string `json:"extension"`
	Bitrate          int64  `json:"bitrate"`
	Duration         int64  `json:"duration"`
	SampleRate       int64  `json:"sample_rate"`
	BitDepth         int64  `json:"bit_depth"`
	AudioSource      string `json:"audio_source"`
	FingerprintSize  []byte `json:"fingerprint_size"`
	FingerprintMtime int64  `json:"fingerprint_mtime"`
	FingerprintCtime int64  `json:"fingerprint_ctime"`
	ExtractorVersion string `json:"extractor_version"`
}

func (q *Queries) InsertShareEntries(ctx context.Context, arg InsertShareEntriesParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, insertShareEntries,
		arg.SnapshotID,
		arg.Ordinal,
		arg.Kind,
		arg.Root,
		arg.Path,
		arg.Name,
		arg.Size,
		arg.Directory,
		arg.Private,
		arg.Vbr,
		arg.VbrKnown,
		arg.Extension,
		arg.Bitrate,
		arg.Duration,
		arg.SampleRate,
		arg.BitDepth,
		arg.AudioSource,
		arg.FingerprintSize,
		arg.FingerprintMtime,
		arg.FingerprintCtime,
		arg.ExtractorVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var ordinal int64
		if err := rows.Scan(&ordinal); err != nil {
			return nil, err
		}
		items = append(items, ordinal)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertShareEntry = `-- name: InsertShareEntry :exec
INSERT INTO share_entries (snapshot_id, ordinal, kind, root, path, name, size, directory, private, vbr, vbr_known, extension, bitrate, duration, sample_rate, bit_depth, audio_source, fingerprint_size, fingerprint_mtime, fingerprint_ctime, extractor_version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertShareEntryParams struct {
	SnapshotID       int64  `json:"snapshot_id"`
	Ordinal          int64  `json:"ordinal"`
	Kind             string `json:"kind"`
	Root             string `json:"root"`
	Path             string `json:"path"`
	Name             string `json:"name"`
	Size             []byte `json:"size"`
	Directory        int64  `json:"directory"`
	Private          int64  `json:"private"`
	Vbr              int64  `json:"vbr"`
	VbrKnown         int64  `json:"vbr_known"`
	Extension        string `json:"extension"`
	Bitrate          int64  `json:"bitrate"`
	Duration         int64  `json:"duration"`
	SampleRate       int64  `json:"sample_rate"`
	BitDepth         int64  `json:"bit_depth"`
	AudioSource      string `json:"audio_source"`
	FingerprintSize  []byte `json:"fingerprint_size"`
	FingerprintMtime int64  `json:"fingerprint_mtime"`
	FingerprintCtime int64  `json:"fingerprint_ctime"`
	ExtractorVersion string `json:"extractor_version"`
}

func (q *Queries) InsertShareEntry(ctx context.Context, arg InsertShareEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertShareEntry,
		arg.SnapshotID,
		arg.Ordinal,
		arg.Kind,
		arg.Root,
		arg.Path,
		arg.Name,
		arg.Size,
		arg.Directory,
		arg.Private,
		arg.Vbr,
		arg.VbrKnown,
		arg.Extension,
		arg.Bitrate,
		arg.Duration,
		arg.SampleRate,
		arg.BitDepth,
		arg.AudioSource,
		arg.FingerprintSize,
		arg.FingerprintMtime,
		arg.FingerprintCtime,
		arg.ExtractorVersion,
	)
	return err
}

const insertShareExclusion = `-- name: InsertShareExclusion :exec
INSERT INTO share_exclusions(snapshot_id, ordinal, pattern) VALUES (?, ?, ?)
`

type InsertShareExclusionParams struct {
	SnapshotID int64  `json:"snapshot_id"`
	Ordinal    int64  `json:"ordinal"`
	Pattern    string `json:"pattern"`
}

func (q *Queries) InsertShareExclusion(ctx context.Context, arg InsertShareExclusionParams) error {
	_, err := q.db.ExecContext(ctx, insertShareExclusion, arg.SnapshotID, arg.Ordinal, arg.Pattern)
	return err
}

const insertShareExclusions = `-- name: InsertShareExclusions :many
INSERT INTO share_exclusions(snapshot_id, ordinal, pattern) VALUES (?, ?, ?) RETURNING ordinal
`

type InsertShareExclusionsParams struct {
	SnapshotID int64  `json:"snapshot_id"`
	Ordinal    int64  `json:"ordinal"`
	Pattern    string `json:"pattern"`
}

func (q *Queries) InsertShareExclusions(ctx context.Context, arg InsertShareExclusionsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, insertShareExclusions, arg.SnapshotID, arg.Ordinal, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var ordinal int64
		if err := rows.Scan(&ordinal); err != nil {
			return nil, err
		}
		items = append(items, ordinal)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertShareRoot = `-- name: InsertShareRoot :exec
INSERT INTO share_roots(snapshot_id, ordinal, name, path) VALUES (?, ?, ?, ?)
`

type InsertShareRootParams struct {
	SnapshotID int64  `json:"snapshot_id"`
	Ordinal    int64  `json:"ordinal"`
	Name       string `json:"name"`
	Path       string `json:"path"`
}

func (q *Queries) InsertShareRoot(ctx context.Context, arg InsertShareRootParams) error {
	_, err := q.db.ExecContext(ctx, insertShareRoot,
		arg.SnapshotID,
		arg.Ordinal,
		arg.Name,
		arg.Path,
	)
	return err
}

const insertShareRoots = `-- name: InsertShareRoots :many
INSERT INTO share_roots(snapshot_id, ordinal, name, path) VALUES (?, ?, ?, ?) RETURNING ordinal
`

type InsertShareRootsParams struct {
	SnapshotID int64  `json:"snapshot_id"`
	Ordinal    int64  `json:"ordinal"`
	Name       string `json:"name"`
	Path       string `json:"path"`
}

func (q *Queries) InsertShareRoots(ctx context.Context, arg InsertShareRootsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, insertShareRoots,
		arg.SnapshotID,
		arg.Ordinal,
		arg.Name,
		arg.Path,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var ordinal int64
		if err := rows.Scan(&ordinal); err != nil {
			return nil, err
		}
		items = append(items, ordinal)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectableShareSnapshots = `-- name: ListCollectableShareSnapshots :many
SELECT s.id, s.source, s.normalized_username, s.username, s.saved_at, s.state, s.created_at
FROM share_snapshots AS s
WHERE s.state = 'staging'
   OR (s.state = 'published'
       AND NOT EXISTS (SELECT 1 FROM share_heads AS h WHERE h.snapshot_id = s.id))
ORDER BY s.id
`

func (q *Queries) ListCollectableShareSnapshots(ctx context.Context) ([]ShareSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listCollectableShareSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareSnapshot
	for rows.Next() {
		var i ShareSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.NormalizedUsername,
			&i.Username,
			&i.SavedAt,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareEntries = `-- name: ListShareEntries :many
SELECT snapshot_id, ordinal, kind, root, path, name, size, directory, private, vbr, vbr_known, extension, bitrate, duration, sample_rate, bit_depth, audio_source, fingerprint_size, fingerprint_mtime, fingerprint_ctime, extractor_version
FROM share_entries WHERE snapshot_id = ? ORDER BY ordinal
`

func (q *Queries) ListShareEntries(ctx context.Context, snapshotID int64) ([]ShareEntry, error) {
	rows, err := q.db.QueryContext(ctx, listShareEntries, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareEntry
	for rows.Next() {
		var i ShareEntry
		if err := rows.Scan(
			&i.SnapshotID,
			&i.Ordinal,
			&i.Kind,
			&i.Root,
			&i.Path,
			&i.Name,
			&i.Size,
			&i.Directory,
			&i.Private,
			&i.Vbr,
			&i.VbrKnown,
			&i.Extension,
			&i.Bitrate,
			&i.Duration,
			&i.SampleRate,
			&i.BitDepth,
			&i.AudioSource,
			&i.FingerprintSize,
			&i.FingerprintMtime,
			&i.FingerprintCtime,
			&i.ExtractorVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareExclusions = `-- name: ListShareExclusions :many
SELECT snapshot_id, ordinal, pattern FROM share_exclusions
WHERE snapshot_id = ? ORDER BY ordinal
`

func (q *Queries) ListShareExclusions(ctx context.Context, snapshotID int64) ([]ShareExclusion, error) {
	rows, err := q.db.QueryContext(ctx, listShareExclusions, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareExclusion
	for rows.Next() {
		var i ShareExclusion
		if err := rows.Scan(&i.SnapshotID, &i.Ordinal, &i.Pattern); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareHeads = `-- name: ListShareHeads :many
SELECT source, normalized_username, snapshot_id FROM share_heads ORDER BY source, normalized_username
`

func (q *Queries) ListShareHeads(ctx context.Context) ([]ShareHead, error) {
	rows, err := q.db.QueryContext(ctx, listShareHeads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareHead
	for rows.Next() {
		var i ShareHead
		if err := rows.Scan(&i.Source, &i.NormalizedUsername, &i.SnapshotID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareRoots = `-- name: ListShareRoots :many
SELECT snapshot_id, ordinal, name, path FROM share_roots
WHERE snapshot_id = ? ORDER BY ordinal
`

func (q *Queries) ListShareRoots(ctx context.Context, snapshotID int64) ([]ShareRoot, error) {
	rows, err := q.db.QueryContext(ctx, listShareRoots, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareRoot
	for rows.Next() {
		var i ShareRoot
		if err := rows.Scan(
			&i.SnapshotID,
			&i.Ordinal,
			&i.Name,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishShareSnapshot = `-- name: PublishShareSnapshot :execresult
UPDATE share_snapshots SET state = 'published' WHERE id = ? AND state = 'staging'
`

func (q *Queries) PublishShareSnapshot(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, publishShareSnapshot, id)
}

const setShareHead = `-- name: SetShareHead :exec
INSERT INTO share_heads(source, normalized_username, snapshot_id) VALUES (?, ?, ?)
ON CONFLICT(source, normalized_username) DO UPDATE SET snapshot_id = excluded.snapshot_id
`

type SetShareHeadParams struct {
	Source             string `json:"source"`
	NormalizedUsername string `json:"normalized_username"`
	SnapshotID         int64  `json:"snapshot_id"`
}

func (q *Queries) SetShareHead(ctx context.Context, arg SetShareHeadParams) error {
	_, err := q.db.ExecContext(ctx, setShareHead, arg.Source, arg.NormalizedUsername, arg.SnapshotID)
	return err
}
