// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: state.sql

package db

import (
	"context"
)

const deleteActiveAttempt = `-- name: DeleteActiveAttempt :exec
DELETE FROM active_attempts WHERE id = ?
`

func (q *Queries) DeleteActiveAttempt(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteActiveAttempt, id)
	return err
}

const deleteAllActiveAttempts = `-- name: DeleteAllActiveAttempts :exec
DELETE FROM active_attempts
`

func (q *Queries) DeleteAllActiveAttempts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllActiveAttempts)
	return err
}

const deleteDownload = `-- name: DeleteDownload :exec
DELETE FROM downloads WHERE id = ?
`

func (q *Queries) DeleteDownload(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDownload, id)
	return err
}

const deleteUpload = `-- name: DeleteUpload :exec
DELETE FROM uploads WHERE id = ?
`

func (q *Queries) DeleteUpload(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUpload, id)
	return err
}

const getActiveAttempt = `-- name: GetActiveAttempt :one
SELECT id, transfer_id, attempt, direction, username, filename, event_id, payload
FROM active_attempts WHERE id = ?
`

func (q *Queries) GetActiveAttempt(ctx context.Context, id string) (ActiveAttempt, error) {
	row := q.db.QueryRowContext(ctx, getActiveAttempt, id)
	var i ActiveAttempt
	err := row.Scan(
		&i.ID,
		&i.TransferID,
		&i.Attempt,
		&i.Direction,
		&i.Username,
		&i.Filename,
		&i.EventID,
		&i.Payload,
	)
	return i, err
}

const getDownload = `-- name: GetDownload :one
SELECT id, stats_account, filter_bypass, username, filename, size, offset, download_dir, destination, state, retry_at, error, created_at, updated_at
FROM downloads WHERE id = ?
`

func (q *Queries) GetDownload(ctx context.Context, id string) (Download, error) {
	row := q.db.QueryRowContext(ctx, getDownload, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.StatsAccount,
		&i.FilterBypass,
		&i.Username,
		&i.Filename,
		&i.Size,
		&i.Offset,
		&i.DownloadDir,
		&i.Destination,
		&i.State,
		&i.RetryAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStateMeta = `-- name: GetStateMeta :one
SELECT id, download_sequence, upload_sequence, upload_queue_sequence, wishlist_sequence, history_sequence, stats_since
FROM state_meta WHERE id = 1
`

func (q *Queries) GetStateMeta(ctx context.Context) (StateMetum, error) {
	row := q.db.QueryRowContext(ctx, getStateMeta)
	var i StateMetum
	err := row.Scan(
		&i.ID,
		&i.DownloadSequence,
		&i.UploadSequence,
		&i.UploadQueueSequence,
		&i.WishlistSequence,
		&i.HistorySequence,
		&i.StatsSince,
	)
	return i, err
}

const getUpload = `-- name: GetUpload :one
SELECT id, account, username, filename, direction, state, done, total, elapsed_ms, speed_bps, eta_seconds, queue, error, queue_order, fingerprint, created_at, queued_at, updated_at, recoverable
FROM uploads WHERE id = ?
`

func (q *Queries) GetUpload(ctx context.Context, id string) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getUpload, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Account,
		&i.Username,
		&i.Filename,
		&i.Direction,
		&i.State,
		&i.Done,
		&i.Total,
		&i.ElapsedMs,
		&i.SpeedBps,
		&i.EtaSeconds,
		&i.Queue,
		&i.Error,
		&i.QueueOrder,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.UpdatedAt,
		&i.Recoverable,
	)
	return i, err
}

const listActiveAttempts = `-- name: ListActiveAttempts :many
SELECT id, transfer_id, attempt, direction, username, filename, event_id, payload
FROM active_attempts ORDER BY id
`

func (q *Queries) ListActiveAttempts(ctx context.Context) ([]ActiveAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listActiveAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveAttempt
	for rows.Next() {
		var i ActiveAttempt
		if err := rows.Scan(
			&i.ID,
			&i.TransferID,
			&i.Attempt,
			&i.Direction,
			&i.Username,
			&i.Filename,
			&i.EventID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloads = `-- name: ListDownloads :many
SELECT id, stats_account, filter_bypass, username, filename, size, offset, download_dir, destination, state, retry_at, error, created_at, updated_at
FROM downloads ORDER BY rowid
`

func (q *Queries) ListDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Download
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.StatsAccount,
			&i.FilterBypass,
			&i.Username,
			&i.Filename,
			&i.Size,
			&i.Offset,
			&i.DownloadDir,
			&i.Destination,
			&i.State,
			&i.RetryAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUploads = `-- name: ListUploads :many
SELECT id, account, username, filename, direction, state, done, total, elapsed_ms, speed_bps, eta_seconds, queue, error, queue_order, fingerprint, created_at, queued_at, updated_at, recoverable
FROM uploads ORDER BY rowid
`

func (q *Queries) ListUploads(ctx context.Context) ([]Upload, error) {
	rows, err := q.db.QueryContext(ctx, listUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upload
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.Account,
			&i.Username,
			&i.Filename,
			&i.Direction,
			&i.State,
			&i.Done,
			&i.Total,
			&i.ElapsedMs,
			&i.SpeedBps,
			&i.EtaSeconds,
			&i.Queue,
			&i.Error,
			&i.QueueOrder,
			&i.Fingerprint,
			&i.CreatedAt,
			&i.QueuedAt,
			&i.UpdatedAt,
			&i.Recoverable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDownloadSequence = `-- name: SetDownloadSequence :exec
UPDATE state_meta SET download_sequence = ?1 WHERE id = 1
`

func (q *Queries) SetDownloadSequence(ctx context.Context, sequence []byte) error {
	_, err := q.db.ExecContext(ctx, setDownloadSequence, sequence)
	return err
}

const setHistorySequence = `-- name: SetHistorySequence :exec
UPDATE state_meta SET history_sequence = ?1 WHERE id = 1
`

func (q *Queries) SetHistorySequence(ctx context.Context, sequence []byte) error {
	_, err := q.db.ExecContext(ctx, setHistorySequence, sequence)
	return err
}

const setStatsSince = `-- name: SetStatsSince :exec
UPDATE state_meta SET stats_since = ?1 WHERE id = 1
`

func (q *Queries) SetStatsSince(ctx context.Context, statsSince *int64) error {
	_, err := q.db.ExecContext(ctx, setStatsSince, statsSince)
	return err
}

const setUploadQueueSequence = `-- name: SetUploadQueueSequence :exec
UPDATE state_meta SET upload_queue_sequence = ?1 WHERE id = 1
`

func (q *Queries) SetUploadQueueSequence(ctx context.Context, sequence []byte) error {
	_, err := q.db.ExecContext(ctx, setUploadQueueSequence, sequence)
	return err
}

const setUploadSequence = `-- name: SetUploadSequence :exec
UPDATE state_meta SET upload_sequence = ?1 WHERE id = 1
`

func (q *Queries) SetUploadSequence(ctx context.Context, sequence []byte) error {
	_, err := q.db.ExecContext(ctx, setUploadSequence, sequence)
	return err
}

const setWishlistSequence = `-- name: SetWishlistSequence :exec
UPDATE state_meta SET wishlist_sequence = ?1 WHERE id = 1
`

func (q *Queries) SetWishlistSequence(ctx context.Context, sequence []byte) error {
	_, err := q.db.ExecContext(ctx, setWishlistSequence, sequence)
	return err
}

const updateDownloadProgress = `-- name: UpdateDownloadProgress :exec
UPDATE downloads SET offset = ?, updated_at = ? WHERE id = ?
`

type UpdateDownloadProgressParams struct {
	Offset    []byte `json:"offset"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateDownloadProgress(ctx context.Context, arg UpdateDownloadProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadProgress, arg.Offset, arg.UpdatedAt, arg.ID)
	return err
}

const updateDownloadState = `-- name: UpdateDownloadState :exec
UPDATE downloads SET state = ?, error = ?, retry_at = ?, updated_at = ? WHERE id = ?
`

type UpdateDownloadStateParams struct {
	State     string `json:"state"`
	Error     string `json:"error"`
	RetryAt   *int64 `json:"retry_at"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateDownloadState(ctx context.Context, arg UpdateDownloadStateParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadState,
		arg.State,
		arg.Error,
		arg.RetryAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUploadProgress = `-- name: UpdateUploadProgress :exec
UPDATE uploads SET done = ?, elapsed_ms = ?, speed_bps = ?, eta_seconds = ?, updated_at = ? WHERE id = ?
`

type UpdateUploadProgressParams struct {
	Done       []byte `json:"done"`
	ElapsedMs  []byte `json:"elapsed_ms"`
	SpeedBps   []byte `json:"speed_bps"`
	EtaSeconds []byte `json:"eta_seconds"`
	UpdatedAt  int64  `json:"updated_at"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateUploadProgress(ctx context.Context, arg UpdateUploadProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadProgress,
		arg.Done,
		arg.ElapsedMs,
		arg.SpeedBps,
		arg.EtaSeconds,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUploadState = `-- name: UpdateUploadState :exec
UPDATE uploads SET state = ?, error = ?, recoverable = ?, updated_at = ? WHERE id = ?
`

type UpdateUploadStateParams struct {
	State       string `json:"state"`
	Error       string `json:"error"`
	Recoverable int64  `json:"recoverable"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateUploadState(ctx context.Context, arg UpdateUploadStateParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadState,
		arg.State,
		arg.Error,
		arg.Recoverable,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const upsertActiveAttempt = `-- name: UpsertActiveAttempt :exec
INSERT INTO active_attempts (id, transfer_id, attempt, direction, username, filename, event_id, payload)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET transfer_id=excluded.transfer_id, attempt=excluded.attempt,
 direction=excluded.direction, username=excluded.username, filename=excluded.filename,
 event_id=excluded.event_id, payload=excluded.payload
`

type UpsertActiveAttemptParams struct {
	ID         string `json:"id"`
	TransferID string `json:"transfer_id"`
	Attempt    []byte `json:"attempt"`
	Direction  string `json:"direction"`
	Username   string `json:"username"`
	Filename   string `json:"filename"`
	EventID    string `json:"event_id"`
	Payload    []byte `json:"payload"`
}

func (q *Queries) UpsertActiveAttempt(ctx context.Context, arg UpsertActiveAttemptParams) error {
	_, err := q.db.ExecContext(ctx, upsertActiveAttempt,
		arg.ID,
		arg.TransferID,
		arg.Attempt,
		arg.Direction,
		arg.Username,
		arg.Filename,
		arg.EventID,
		arg.Payload,
	)
	return err
}

const upsertDownload = `-- name: UpsertDownload :exec
INSERT INTO downloads (id, stats_account, filter_bypass, username, filename, size, offset, download_dir, destination, state, retry_at, error, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
 stats_account=excluded.stats_account, filter_bypass=excluded.filter_bypass, username=excluded.username,
 filename=excluded.filename, size=excluded.size, offset=excluded.offset, download_dir=excluded.download_dir,
 destination=excluded.destination, state=excluded.state, retry_at=excluded.retry_at, error=excluded.error,
 created_at=excluded.created_at, updated_at=excluded.updated_at
`

type UpsertDownloadParams struct {
	ID           string `json:"id"`
	StatsAccount string `json:"stats_account"`
	FilterBypass int64  `json:"filter_bypass"`
	Username     string `json:"username"`
	Filename     string `json:"filename"`
	Size         []byte `json:"size"`
	Offset       []byte `json:"offset"`
	DownloadDir  string `json:"download_dir"`
	Destination  string `json:"destination"`
	State        string `json:"state"`
	RetryAt      *int64 `json:"retry_at"`
	Error        string `json:"error"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertDownload(ctx context.Context, arg UpsertDownloadParams) error {
	_, err := q.db.ExecContext(ctx, upsertDownload,
		arg.ID,
		arg.StatsAccount,
		arg.FilterBypass,
		arg.Username,
		arg.Filename,
		arg.Size,
		arg.Offset,
		arg.DownloadDir,
		arg.Destination,
		arg.State,
		arg.RetryAt,
		arg.Error,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertUpload = `-- name: UpsertUpload :exec
INSERT INTO uploads (id, account, username, filename, direction, state, done, total, elapsed_ms, speed_bps, eta_seconds, queue, error, queue_order, fingerprint, created_at, queued_at, updated_at, recoverable)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
 account=excluded.account, username=excluded.username, filename=excluded.filename, direction=excluded.direction,
 state=excluded.state, done=excluded.done, total=excluded.total, elapsed_ms=excluded.elapsed_ms,
 speed_bps=excluded.speed_bps, eta_seconds=excluded.eta_seconds, queue=excluded.queue, error=excluded.error,
 queue_order=excluded.queue_order, fingerprint=excluded.fingerprint, created_at=excluded.created_at,
 queued_at=excluded.queued_at, updated_at=excluded.updated_at, recoverable=excluded.recoverable
`

type UpsertUploadParams struct {
	ID          string `json:"id"`
	Account     string `json:"account"`
	Username    string `json:"username"`
	Filename    string `json:"filename"`
	Direction   string `json:"direction"`
	State       string `json:"state"`
	Done        []byte `json:"done"`
	Total       []byte `json:"total"`
	ElapsedMs   []byte `json:"elapsed_ms"`
	SpeedBps    []byte `json:"speed_bps"`
	EtaSeconds  []byte `json:"eta_seconds"`
	Queue       int64  `json:"queue"`
	Error       string `json:"error"`
	QueueOrder  []byte `json:"queue_order"`
	Fingerprint string `json:"fingerprint"`
	CreatedAt   int64  `json:"created_at"`
	QueuedAt    int64  `json:"queued_at"`
	UpdatedAt   int64  `json:"updated_at"`
	Recoverable int64  `json:"recoverable"`
}

func (q *Queries) UpsertUpload(ctx context.Context, arg UpsertUploadParams) error {
	_, err := q.db.ExecContext(ctx, upsertUpload,
		arg.ID,
		arg.Account,
		arg.Username,
		arg.Filename,
		arg.Direction,
		arg.State,
		arg.Done,
		arg.Total,
		arg.ElapsedMs,
		arg.SpeedBps,
		arg.EtaSeconds,
		arg.Queue,
		arg.Error,
		arg.QueueOrder,
		arg.Fingerprint,
		arg.CreatedAt,
		arg.QueuedAt,
		arg.UpdatedAt,
		arg.Recoverable,
	)
	return err
}
