// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
	"database/sql"
)

const countDailyTotalsBefore = `-- name: CountDailyTotalsBefore :one
SELECT count(*) FROM totals WHERE day <> '' AND day < ?
`

func (q *Queries) CountDailyTotalsBefore(ctx context.Context, day *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDailyTotalsBefore, day)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsBefore = `-- name: CountEventsBefore :one
SELECT count(*) FROM events WHERE at < ?
`

func (q *Queries) CountEventsBefore(ctx context.Context, at *int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsBefore, at)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDailyTotalsBefore = `-- name: DeleteDailyTotalsBefore :exec
DELETE FROM totals WHERE day <> '' AND day < ?
`

func (q *Queries) DeleteDailyTotalsBefore(ctx context.Context, day *string) error {
	_, err := q.db.ExecContext(ctx, deleteDailyTotalsBefore, day)
	return err
}

const deleteEventsBefore = `-- name: DeleteEventsBefore :exec
DELETE FROM events WHERE at < ?
`

func (q *Queries) DeleteEventsBefore(ctx context.Context, at *int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventsBefore, at)
	return err
}

const getTotalsData = `-- name: GetTotalsData :one
SELECT data FROM totals
WHERE account = ? AND peer = ? AND direction = ? AND session = ? AND day = ?
`

type GetTotalsDataParams struct {
	Account   *string `json:"account"`
	Peer      *string `json:"peer"`
	Direction *string `json:"direction"`
	Session   *string `json:"session"`
	Day       *string `json:"day"`
}

func (q *Queries) GetTotalsData(ctx context.Context, arg GetTotalsDataParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getTotalsData,
		arg.Account,
		arg.Peer,
		arg.Direction,
		arg.Session,
		arg.Day,
	)
	var data string
	err := row.Scan(&data)
	return data, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events(id, account, peer, direction, session, kind, at, data)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID        string  `json:"id"`
	Account   *string `json:"account"`
	Peer      *string `json:"peer"`
	Direction *string `json:"direction"`
	Session   *string `json:"session"`
	Kind      *string `json:"kind"`
	At        *int64  `json:"at"`
	Data      string  `json:"data"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.Account,
		arg.Peer,
		arg.Direction,
		arg.Session,
		arg.Kind,
		arg.At,
		arg.Data,
	)
	return err
}

const insertSeen = `-- name: InsertSeen :execresult
INSERT OR IGNORE INTO seen(id) VALUES (?)
`

func (q *Queries) InsertSeen(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertSeen, id)
}

const upsertTotals = `-- name: UpsertTotals :exec
INSERT INTO totals(account, peer, direction, session, day, data)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(account, peer, direction, session, day)
DO UPDATE SET data = excluded.data
`

type UpsertTotalsParams struct {
	Account   *string `json:"account"`
	Peer      *string `json:"peer"`
	Direction *string `json:"direction"`
	Session   *string `json:"session"`
	Day       *string `json:"day"`
	Data      string  `json:"data"`
}

func (q *Queries) UpsertTotals(ctx context.Context, arg UpsertTotalsParams) error {
	_, err := q.db.ExecContext(ctx, upsertTotals,
		arg.Account,
		arg.Peer,
		arg.Direction,
		arg.Session,
		arg.Day,
		arg.Data,
	)
	return err
}
