// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ui.sql

package db

import (
	"context"
)

const clearHistoryKind = `-- name: ClearHistoryKind :exec
DELETE FROM history WHERE kind = ?
`

func (q *Queries) ClearHistoryKind(ctx context.Context, kind string) error {
	_, err := q.db.ExecContext(ctx, clearHistoryKind, kind)
	return err
}

const deleteHistory = `-- name: DeleteHistory :exec
DELETE FROM history WHERE kind = ? AND value = ?
`

type DeleteHistoryParams struct {
	Kind  string `json:"kind"`
	Value string `json:"value"`
}

func (q *Queries) DeleteHistory(ctx context.Context, arg DeleteHistoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteHistory, arg.Kind, arg.Value)
	return err
}

const deleteUIPreference = `-- name: DeleteUIPreference :exec
DELETE FROM ui_preferences WHERE key = ?
`

func (q *Queries) DeleteUIPreference(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteUIPreference, key)
	return err
}

const deleteWishlist = `-- name: DeleteWishlist :exec
DELETE FROM wishlist WHERE id = ?
`

func (q *Queries) DeleteWishlist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWishlist, id)
	return err
}

const getUIPreference = `-- name: GetUIPreference :one
SELECT key, value FROM ui_preferences WHERE key = ?
`

func (q *Queries) GetUIPreference(ctx context.Context, key string) (UiPreference, error) {
	row := q.db.QueryRowContext(ctx, getUIPreference, key)
	var i UiPreference
	err := row.Scan(&i.Key, &i.Value)
	return i, err
}

const getWishlist = `-- name: GetWishlist :one
SELECT id, query, filter, added_at, last_run_at, result_count, result_signature, unread, notification_sequence
FROM wishlist WHERE id = ?
`

func (q *Queries) GetWishlist(ctx context.Context, id string) (Wishlist, error) {
	row := q.db.QueryRowContext(ctx, getWishlist, id)
	var i Wishlist
	err := row.Scan(
		&i.ID,
		&i.Query,
		&i.Filter,
		&i.AddedAt,
		&i.LastRunAt,
		&i.ResultCount,
		&i.ResultSignature,
		&i.Unread,
		&i.NotificationSequence,
	)
	return i, err
}

const listHistory = `-- name: ListHistory :many
SELECT kind, value, recency FROM history WHERE kind = ? ORDER BY recency DESC, value
`

func (q *Queries) ListHistory(ctx context.Context, kind string) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(&i.Kind, &i.Value, &i.Recency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUIPreferences = `-- name: ListUIPreferences :many
SELECT key, value FROM ui_preferences ORDER BY key
`

func (q *Queries) ListUIPreferences(ctx context.Context) ([]UiPreference, error) {
	rows, err := q.db.QueryContext(ctx, listUIPreferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UiPreference
	for rows.Next() {
		var i UiPreference
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishlist = `-- name: ListWishlist :many
SELECT id, query, filter, added_at, last_run_at, result_count, result_signature, unread, notification_sequence
FROM wishlist ORDER BY rowid
`

func (q *Queries) ListWishlist(ctx context.Context) ([]Wishlist, error) {
	rows, err := q.db.QueryContext(ctx, listWishlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wishlist
	for rows.Next() {
		var i Wishlist
		if err := rows.Scan(
			&i.ID,
			&i.Query,
			&i.Filter,
			&i.AddedAt,
			&i.LastRunAt,
			&i.ResultCount,
			&i.ResultSignature,
			&i.Unread,
			&i.NotificationSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimHistory = `-- name: TrimHistory :exec
DELETE FROM history
WHERE history.kind = ?
  AND history.value IN (
    SELECT h.value FROM history AS h
    WHERE h.kind = ?
    ORDER BY h.recency DESC, h.value
    LIMIT -1 OFFSET ?
  )
`

type TrimHistoryParams struct {
	Kind   string `json:"kind"`
	Kind_2 string `json:"kind_2"`
	Offset int64  `json:"offset"`
}

func (q *Queries) TrimHistory(ctx context.Context, arg TrimHistoryParams) error {
	_, err := q.db.ExecContext(ctx, trimHistory, arg.Kind, arg.Kind_2, arg.Offset)
	return err
}

const upsertHistory = `-- name: UpsertHistory :exec
INSERT OR REPLACE INTO history(kind, value, recency) VALUES (?, ?, ?)
`

type UpsertHistoryParams struct {
	Kind    string `json:"kind"`
	Value   string `json:"value"`
	Recency []byte `json:"recency"`
}

func (q *Queries) UpsertHistory(ctx context.Context, arg UpsertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertHistory, arg.Kind, arg.Value, arg.Recency)
	return err
}

const upsertUIPreference = `-- name: UpsertUIPreference :exec
INSERT INTO ui_preferences(key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertUIPreferenceParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertUIPreference(ctx context.Context, arg UpsertUIPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertUIPreference, arg.Key, arg.Value)
	return err
}

const upsertWishlist = `-- name: UpsertWishlist :exec
INSERT INTO wishlist (id, query, filter, added_at, last_run_at, result_count, result_signature, unread, notification_sequence)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET query=excluded.query, filter=excluded.filter, added_at=excluded.added_at,
 last_run_at=excluded.last_run_at, result_count=excluded.result_count, result_signature=excluded.result_signature,
 unread=excluded.unread, notification_sequence=excluded.notification_sequence
`

type UpsertWishlistParams struct {
	ID                   string `json:"id"`
	Query                string `json:"query"`
	Filter               string `json:"filter"`
	AddedAt              int64  `json:"added_at"`
	LastRunAt            *int64 `json:"last_run_at"`
	ResultCount          int64  `json:"result_count"`
	ResultSignature      string `json:"result_signature"`
	Unread               int64  `json:"unread"`
	NotificationSequence []byte `json:"notification_sequence"`
}

func (q *Queries) UpsertWishlist(ctx context.Context, arg UpsertWishlistParams) error {
	_, err := q.db.ExecContext(ctx, upsertWishlist,
		arg.ID,
		arg.Query,
		arg.Filter,
		arg.AddedAt,
		arg.LastRunAt,
		arg.ResultCount,
		arg.ResultSignature,
		arg.Unread,
		arg.NotificationSequence,
	)
	return err
}
